import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Cortège",
  robots: { index: true, follow: true },
};

const wrap: React.CSSProperties = {
  maxWidth: 720, margin: "0 auto", padding: "48px 24px 80px",
  color: "var(--color-text)", fontFamily: "var(--font-body)", lineHeight: 1.65, fontSize: 14.5,
};
const h1: React.CSSProperties = { fontFamily: "var(--font-heading)", fontSize: 26, fontWeight: 800, marginBottom: 6 };
const h2: React.CSSProperties = { fontFamily: "var(--font-heading)", fontSize: 16, fontWeight: 700, marginTop: 34, marginBottom: 10, color: "var(--color-text)" };
const p: React.CSSProperties = { color: "var(--color-text-soft)", margin: "0 0 12px" };
const meta: React.CSSProperties = { color: "var(--color-text-faint)", fontSize: 12.5, marginBottom: 30 };

export default function TermsPage() {
  return (
    <div style={wrap}>
      <h1 style={h1}>Terms of Service</h1>
      <p style={meta}>Cortège by Solura Agency · Last updated: July 2026</p>

      <h2 style={h2}>1. The service</h2>
      <p style={p}>
        Cortège is an AI conversational assistant service operated by Solura Agency. A business
        (&ldquo;Client&rdquo;) connects its Telegram bot and/or Instagram account so Cortège can respond to that
        Client&apos;s own customers (&ldquo;End Users&rdquo;) automatically, using information the Client
        provides (pricing, packages, availability, partner vendors, policies).
      </p>

      <h2 style={h2}>2. AI-generated responses</h2>
      <p style={p}>
        Responses are generated by an AI model based on data the Client has provided. While the
        assistant is designed to answer only from that data and to escalate to a human when it lacks
        an answer, AI-generated text can occasionally be incorrect or out of date. Cortège is not a
        substitute for direct confirmation on time-sensitive or high-value matters (e.g. a final
        contract, exact payment terms) — the Client remains responsible for the accuracy of
        information it provides and for confirming details with End Users directly when needed.
      </p>

      <h2 style={h2}>3. Acceptable use</h2>
      <p style={p}>
        The service may not be used to send unsolicited messages, to message End Users outside the
        conversation windows permitted by Telegram or Meta&apos;s platform policies, or for any
        unlawful purpose. Clients are responsible for the accuracy of the business information they
        configure and for their own compliance with applicable consumer-protection and advertising
        rules in their jurisdiction.
      </p>

      <h2 style={h2}>4. Data handling</h2>
      <p style={p}>
        Data collected through the service is handled as described in our{" "}
        <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2 style={h2}>5. Availability and changes</h2>
      <p style={p}>
        We aim to keep the service available and reliable but do not guarantee uninterrupted
        operation. Features may change as the product evolves; we&apos;ll make reasonable efforts to
        notify Clients of changes that materially affect how the service works.
      </p>

      <h2 style={h2}>6. Termination</h2>
      <p style={p}>
        A Client may stop using Cortège at any time by contacting us. We may suspend or terminate
        access if the service is used in violation of these terms, applicable law, or the platform
        policies of Telegram or Meta.
      </p>

      <h2 style={h2}>7. Limitation of liability</h2>
      <p style={p}>
        The service is provided on an &ldquo;as is&rdquo; basis. To the extent permitted by law, Solura Agency is
        not liable for indirect or consequential damages arising from use of the service, including
        inaccuracies in AI-generated responses.
      </p>

      <h2 style={h2}>8. Contact</h2>
      <p style={p}>
        Solura Agency — <a href="mailto:info@solura.agency">info@solura.agency</a>
      </p>
    </div>
  );
}
